[".dir_colors"]
    type = "file"
    url = "https://raw.githubusercontent.com/arcticicestudio/nord-dircolors/develop/src/dir_colors"
    refreshPeriod = "168h"
[".config/karabiner/assets/complex_modifications/japanese.json"]
    type = "file"
    url = "https://ke-complex-modifications.pqrs.org/json/japanese.json"
    refreshPeriod = "168h"
["antigen.zsh"]
    type = "file"
    url = "https://git.io/antigen"
    refreshPeriod = "168h"
[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
