# Don't ask for confirmations
#assume_yes = true

# Disable specific steps - same options as the command line flag
disable = ["git_repos", "node", "gem", "deno"]

# Ignore failures for these steps
#ignore_failures = ["powershell"]

# Run specific steps - same options as the command line flag
#only = ["system", "emacs"]

# Do not ask to retry failed steps (default: false)
no_retry = true

# Run inside tmux
run_in_tmux = false

[brew]
#greedy_cask = true
 